modLoader = "javafml"
loaderVersion = "[33,)"
license = "LGPLv3"
issueTrackerURL = ""
[[mods]]
modId = "improvedfloatingislands"
version = "1.0"
displayName = "Improved Floating Islands"
displayURL = ""
logoFile = "icon.png"
credits = ""
authors = "Corgi Taco"
description = '''
A mod that makes floating islands more configurable.
'''
[[dependencies.improvedfloatingislands]]
modId = "forge"
mandatory = true
versionRange = "[33.0.0,)"
ordering = "NONE"
side = "BOTH"
